### ISSUE TITLE
App crashes when update popup comes up

### ISSUE THREAD

**Issue by krisl21** [phoenixlauncher/phoenix#102]
Right after the updater window, app crashes. Manually checking for updates does the same.

**Comment by Shock9616** [comment]
What version of the app are you using? If you're on 0.1.1 it's probably because it was pointing to a test project. If you're on 0.1.2 we're going to need more information because that's the first one where the updater should actually be working, but we don't have a new update out yet so it shouldn't be coming up.

**Comment by jxhug** [comment]
can you also give your OS version and provide logs from `~/Library/Application Support/Phoenix` please?

**Comment by krisl21** [comment]
Yes I was on 0.1.1. New version is working! Thanks.
