### ISSUE TITLE
Package for homebrew

### ISSUE THREAD

**Issue by 0oAstro** [phoenixlauncher/phoenix#188]
**Is your feature request related to a problem? Please describe.**
Thanks for this beautiful software. It would be great if we were to get a homebrew tap (or maybe a package in the official repo, which got rejected earlier for being too obscure afaik)

**Describe the solution you'd like**
A homebrew tap which will serve the phoenix package until it gets merged into the main repo.

**Describe alternatives you've considered**
manually installing it?? lol

**Additional context**
idk if this is required here

**Comment by Shock9616** [comment]
Hi there! Thanks for submitting this request! Getting it working with homebrew is definitely on the roadmap for us, we just haven't gotten around to it yet. We haven't bothered trying to submit to the main repo because of being too obscure, but it's definitely possible that we could set it up as a tap for now. I can probably try and start working on that in a couple days.

**Comment by 0oAstro** [comment]
ah btw i tried to get my hands messy yesterday with this, seems like homebrew only allows signed/notarized applications on the platform :(

sadly phoenix wont have a tap then. closing this pr as a result till the project gets enough funding for notarized builds

**Comment by Shock9616** [comment]
Oh ok that's good to know lol. Thanks for letting me know before I spent hours trying to get it working 😂
