### ISSUE TITLE
add button to pull from igdb api for game metadata

### ISSUE THREAD

**Issue by jxhug** [phoenixlauncher/phoenix#26]

**Comment by elrumo** [comment]
I've thought about having an API for it, but I haven't figured out a way that keeps users from abusing it. I might have to to add rate limits after which you'd need to pay so that I could at least cover the server costs, which is what the ads on the website do.

I'm on holidays at the moment, but I might be willing to do it for free for you guys to test it. Do you have an estimate of how many calls you'd need to make monthly?

**Comment by Shock9616** [comment]
How many calls would be problematic? For testing I can't imagine it would be very much. There's only 3 current devs who would be testing before it's added to a release, and once it is, this is something that each user will do once and then never again. Right now we don't have a very large userbase (our last release only has 12 downloads) but I don't really have any way of telling how many we will have once we release version 1.0.

**Comment by jxhug** [comment]
Yeah we have a very small user-base and won't even be rolling out this feature yet so not many calls will happen.

**Comment by jxhug** [comment]
need to fix dupe devs and pubs

**Comment by jxhug** [comment]
done in igdb

**Comment by jxhug** [comment]
merged in #74

**Comment by elrumo** [comment]
Hey there! I finally came around building an API for macOSicons. Right now it only let's you search for icons, but I might implement the option to limit to certain categories, like games. You can check it out here: https://docs.macosicons.com/

**Comment by jmshgs** [comment]
thanks mate!
