### ISSUE TITLE
add keyboard shortcuts

### ISSUE THREAD

**Issue by jxhug** [PhoenixLauncher/Phoenix#46]
tasks are:
- [x] ~~`⌘ + f` to filter games list (#42)~~
- [x] `⌘ + n` to add a new game
- [x] `⌘ + e` to edit a game
- [x] `⌘ + p` to play a game
- [x] `⌘ + 1-4` to switch sorting categories

**Comment by Shock9616** [comment]
What would be the purpose of adding tabs? It seems to me like it's an unnecessary complication since they're generally used for multitasking (like editing 2 files or having 2 websites open). There's not really any point I can think of to add them.

I agree with the rest of the shortcuts though. The add/edit commands should probably also be added to the right-click menu in the games list.

**Comment by jxhug** [comment]
yeah I only said that because if you go into the view menu you can add tabs already. it's kind of useful I guess so I feel like there's no real point in removing it. may as well go with it!

**Comment by jxhug** [comment]
done in #52
